In [1]:
import os 
import pandas as pd 
from openai import OpenAI
from dotenv import load_dotenv
load_dotenv()

client = OpenAI(
    api_key="sk-7nLKAOapaZy49FIt6QTq0VmeBSsWF9HCAFr7MZd49qubnPU9",
    base_url="https://api.chatanywhere.tech/v1"
)

In [32]:
folder_path = "../builder/txtfile"

In [33]:
file_list = [f for f in os.listdir(folder_path)]

In [34]:
title = []
book_content = []
for f in file_list:
    title.append(f.split(".txt")[0])
    with open(os.path.join(folder_path,f),"r",encoding="utf-8") as f:
        content = f.read()
    book_content.append(content)

In [35]:
df = pd.DataFrame(
    [file_list,
    title,
    book_content]
).T

In [36]:
df.columns = ['file_name',"title","content"]

In [37]:
df

,file_name,title,content
0,BMT65_75 - Turret Indexer Assembly - Troublesh...,BMT65_75 - Turret Indexer Assembly - Troublesh...,## BMT65/75 - Turret Indexer Assembly - Troubl...
1,BMT65_75 Turret - Live Tool Drive - Alignment.txt,BMT65_75 Turret - Live Tool Drive - Alignment,## BMT65/75 Turret - Live Tool Drive - Alignme...
2,Chip Auger - Haas Service Manual.txt,Chip Auger - Haas Service Manual,### 6 - Chip Auger\n\n\n###### https://www.haa...
3,Chip Conveyor - Lathe - Haas Service Manual.txt,Chip Conveyor - Lathe - Haas Service Manual,### 9 - Chip Conveyor - Lathe\n\n\n###### http...
4,Chip Conveyor - UMC - Haas Service Manual.txt,Chip Conveyor - UMC - Haas Service Manual,### 8 - Chip Conveyor - UMC\n\n\n###### https:...
5,Coolant Refill - Calibration.txt,Coolant Refill - Calibration,## Coolant Refill - Calibration\n\n\nhttps://w...
6,Coolant Refill - Haas Service Manual.txt,Coolant Refill - Haas Service Manual,### 10 - Coolant Refill\n\n\n###### https://ww...
7,Drive Belt - Troubleshooting Guide.txt,Drive Belt - Troubleshooting Guide,## Drive Belt - Troubleshooting Guide\n\n\nhtt...
8,Electrical Safety Door Interlocks - Troublesho...,Electrical Safety Door Interlocks - Troublesho...,## Electrical Safety Door Interlocks - Trouble...
9,Foot Pedal - Troubleshooting Guide - NGC.txt,Foot Pedal - Troubleshooting Guide - NGC,## Foot Pedal - Troubleshooting Guide - NGC\n\...
10,Haas Oil Skimmer - Installation - AD0480.txt,Haas Oil Skimmer - Installation - AD0480,## Haas Oil Skimmer - Installation - AD0480\n\...
11,Haas Oil Skimmer - Maintenence - AD0481.txt,Haas Oil Skimmer - Maintenence - AD0481,## Haas Oil Skimmer - Maintenence - AD0481\n\n...
12,Haas Oil Skimmer Troubleshooting Guide.txt,Haas Oil Skimmer Troubleshooting Guide,## Haas Oil Skimmer Troubleshooting Guide\n\n\...
13,High Pressure Flood Coolant - Haas Service Man...,High Pressure Flood Coolant - Haas Service Manual,### 11 - High Pressure Flood Coolant\n\n\n####...
14,HRP - Maintenance - Haas Service Manual.txt,HRP - Maintenance - Haas Service Manual,### 12 - HRP - Maintenance\n\n\n###### https:/...
15,HRP - Troubleshooting - Haas Service Manual.txt,HRP - Troubleshooting - Haas Service Manual,### 13 - HRP - Troubleshooting\n\n\n###### htt...
16,Hydraulic Power Unit - Troubleshooting Guide.txt,Hydraulic Power Unit - Troubleshooting Guide,## Hydraulic Power Unit - Troubleshooting Guid...
17,Hydraulic Tailstock - Troubleshooting Guide.txt,Hydraulic Tailstock - Troubleshooting Guide,## Hydraulic Tailstock - Troubleshooting Guide...
18,ID0014_Rev_A.txt,ID0014_Rev_A,# HPU Inspection Report\n\nLathe HPU Clear Wor...
19,I_O PCB - Troubleshooting Guide - CHC.txt,I_O PCB - Troubleshooting Guide - CHC,## I/O PCB - Troubleshooting Guide - CHC\n\n\n...
20,I_O PCB - Troubleshooting Guide - NGC.txt,I_O PCB - Troubleshooting Guide - NGC,## I/O PCB - Troubleshooting Guide - NGC\n\n\n...
21,Lathe - Maintenance - Haas Service Manual.txt,Lathe - Maintenance - Haas Service Manual,### 20 - Lathe - Maintenance\n\n\n##### https:...
22,Lathe - Parts Catcher - Haas Service Manual.txt,Lathe - Parts Catcher - Haas Service Manual,### 12 - Lathe - Parts Catcher\n\n\n###### htt...
23,Lathe Maintenance Schedule.txt,Lathe Maintenance Schedule,## Lathe Maintenance Schedule\n\n\nhttps://www...
24,Live Tooling - Troubleshooting Guide.txt,Live Tooling - Troubleshooting Guide,## Live Tooling - Troubleshooting Guide\n\n\nh...
25,Mechanical Bijur Lubrication Pump - Troublesho...,Mechanical Bijur Lubrication Pump - Troublesho...,## Mechanical Bijur Lubrication Pump - Trouble...
26,Mist Condenser - Haas Service Manual.txt,Mist Condenser - Haas Service Manual,### 15 - Mist Condenser\n\n\n###### https://ww...
27,Proximity Sensor - Troubleshooting Guide.txt,Proximity Sensor - Troubleshooting Guide,## Proximity Sensor - Troubleshooting Guide\n\...
28,PSUP PCB - Troubleshooting Guide - NGC.txt,PSUP PCB - Troubleshooting Guide - NGC,## PSUP PCB - Troubleshooting Guide - NGC\n\n\...
29,Servo Amplifier - Troubleshooting Guide - CHC.txt,Servo Amplifier - Troubleshooting Guide - CHC,## Servo Amplifier - Troubleshooting Guide - C...
30,Sigma 5 - Axis Servo Motor and Cables - Troubl...,Sigma 5 - Axis Servo Motor and Cables - Troubl...,## Sigma 5 - Axis Servo Motor and Cables - Tro...
31,Solenoid - Troubleshooting Guide.txt,Solenoid - Troubleshooting Guide,## Solenoid - Troubleshooting Guide\n\n\nhttps...
32,Spindle - Lathe - Troubleshooting Guide.txt,Spindle - Lathe - Troubleshooting Guide,## Spindle - Lathe - Troubleshooting Guide\n\n...
33,Spindle Minimum Lubrication System - Troublesh...,Spindle Minimum Lubrication System - Troublesh...,## Spindle Minimum Lubrication System - Troubl...
34,Spindle Non-Contact Encoder (NCE) - Troublesho...,Spindle Non-Contact Encoder (NCE) - Troublesho...,## Spindle Non-Contact Encoder (NCE) - Trouble...
35,Standard Flood Coolant - Haas Service Manual.txt,Standard Flood Coolant - Haas Service Manual,### 3 - Standard Flood Coolant\n\n\n###### htt...
36,Through-Tool Air Blast - Haas Service Manual.txt,Through-Tool Air Blast - Haas Service Manual,### 13 - Through-Tool Air Blast\n\n\n###### ht...
37,TSC-300_1K - Troubleshooting Guide - NGC.txt,TSC-300_1K - Troubleshooting Guide - NGC,## TSC-300/1K - Troubleshooting Guide - NGC\n\...
38,Turret Indexer Assembly - SL-10_30 ST-10_15 - ...,Turret Indexer Assembly - SL-10_30 ST-10_15 - ...,## Turret Indexer Assembly - SL-10/30 ST-10/15...
39,Turret Indexer Assembly - ST-20_55 series - Tr...,Turret Indexer Assembly - ST-20_55 series - Tr...,## Turret Indexer Assembly - ST-20/55 series -...
40,Vector Drive - Troubleshooting Guide - NGC.txt,Vector Drive - Troubleshooting Guide - NGC,## Vector Drive - Troubleshooting Guide - NGC\...
41,VMC Side Mount Tool Changer - Double Arm - Rep...,VMC Side Mount Tool Changer - Double Arm - Rep...,## VMC Side Mount Tool Changer - Double Arm - ...
42,Way Cover - Troubleshooting Guide.txt,Way Cover - Troubleshooting Guide,## Way Cover - Troubleshooting Guide\n\n\nhttp...

In [38]:
def analysis_mamual_book(title,content):
    response = client.chat.completions.create(
        model="deepseek-reasoner",
        messages=[{"role":"system","content":"""我会给你一个一个零件的manual book名称和对应内容，
             #要求：
             1.请帮我提炼出来该零件的名字,
             2.以及manual book里面提供的一写solution,solution只需要是概括性的描述不是具体的操作方案，比如：`make sure the coolant tank float operates correctly`,有多个solution就提取多个，以List的形式返回,
             #Output Format:
             {
             "part_name":提取出来的零件名称,
             "solutions":["make sure the coolant tank float operates correctly",...]#提取出来的solution
             }"""
                   },
                  {"role":"user","content":f"这是manual book的title：{title},这是manual book的内容：{content}"}],
        temperature=0.01
    )
    return response.choices[0].message.content

In [39]:
result = []
for ind,row in df.iterrows():
    print(ind)
    answer = analysis_mamual_book(row['title'],row['content'])
    result.append(answer)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42

In [40]:
result

['\n\n```json\n{\n  "part_name": "Turret Indexer Assembly",\n  "solutions": [\n    "Check the incoming air supply",\n    "Check the voltage to the turret clamp or unclamp solenoid",\n    "Check the turret clamp/unclamp proximity sensor",\n    "Check the piston, internal gears and spring assembly for damage",\n    "Check the internal gears for damage",\n    "Clear obstruction such as chips between tool turret and housing",\n    "Check if air is bypassing the turret piston quad-ring",\n    "Check the spring force",\n    "Verify the air pressure and flow during tool change",\n    "Test the clamp/unclamp proximity sensor functionality",\n    "Check servo motor cables for contamination or grounding issues",\n    "Measure turret pop-out distance during unclamp/clamp cycles",\n    "Inspect solenoid voltage during M43/M44 operations",\n    "Calculate spring clamp force using applied air pressure and piston surface area"\n  ]\n}\n```',
 '\n\n```json\n{\n  "part_name": "BMT65/75 Turret Live Tool Drive",\n  "solutions": [\n    "Check the alignment of the live tool drive in the Z axis using a dial indicator",\n    "Add or remove shims if the Z-axis alignment exceeds 0.002\\" tolerance",\n    "Perform BMT Live Tooling Drive Alignment procedure after confirming Z-axis alignment"\n  ]\n}\n```',
 '\n\n```json\n{\n  "part_name": "Chip Auger",\n  "solutions": [\n    "Inspect the auger motor start capacitor for damage",\n    "Verify the voltage at the I/O PCB and the motor",\n    "Check for a short in the motor or the cable",\n    "Check the fuses on the I/O PCB",\n    "Ensure parameters are set correctly (e.g., Parameter 209.03/209.17)",\n    "Clear all chips and obstructions from the auger trough and chip chute",\n    "Check the motor for burnout or binding if overcurrent is detected",\n    "Inspect the auger motor and coupling for mechanical issues",\n    "Inspect the auger for wear at the end",\n    "Check if the auger is bent by rolling it on the floor",\n    "Update machine software to resolve automatic restart issues",\n    "Ensure conveyor cycle timers follow updated software logic"\n  ]\n}\n```',
 '\n\n```json\n{\n  "part_name": "Chip Conveyor",\n  "solutions": [\n    "Check for a short circuit in the motor or the cable",\n    "Verify voltage at I/O PCB and the motor",\n    "Check the fuses on the I/O PCB",\n    "Inspect motor capacitor for damage",\n    "Clear excessive chips and any obstructions",\n    "Inspect conveyor belt and repair or replace",\n    "Adjust the belt tension",\n    "Ensure the conveyor motor capacitor operates correctly",\n    "Check the discrete input CHIP_CONVEYOR_OVERCURRENT cycles",\n    "Update machine software to the latest version",\n    "Verify motor wiring configuration",\n    "Check for coolant contamination in motor cable connections",\n    "Inspect conveyor drive shaft and keyway for damage"\n  ]\n}\n```',
 '\n\n```json\n{\n  "part_name": "Chip Conveyor",\n  "solutions": [\n    "ensure the conveyor drive cable is routed properly to avoid damage",\n    "verify voltage at the I/O PCB and motor for correct operation",\n    "adjust the conveyor belt tension if incorrect",\n    "clear excessive chips and obstructions from the conveyor",\n    "inspect and replace a damaged conveyor belt",\n    "check for short circuits in the motor or cable",\n    "verify proper installation of spillway and mating brackets",\n    "ensure the extension panel is wedged between casting and conveyor",\n    "reinstall gaskets to prevent leaks after conveyor installation",\n    "update machine software to resolve automatic conveyor restart issues"\n  ]\n}\n```',
 '\n\n```json\n{\n  "part_name": "Coolant Refill System",\n  "solutions": [\n    "Adjust the Concentrate Adjustment value based on measured coolant concentration to maintain desired levels",\n    "Ensure the filler hose is properly installed and does not touch the coolant",\n    "Add powdered/liquid coolant additives only in the coolant tank, not the refill tank, to prevent damage"\n  ]\n}\n```',
 '\n\n```json\n{\n  "part_name": "Coolant Refill",\n  "solutions": [\n    "make sure the coolant tank float operates correctly",\n    "ensure the water supply pressure is between 40-100 psi (2.8-6.9 bar)",\n    "install and maintain the screen filter in the water supply hose fitting",\n    "clean clogged screen filters regularly",\n    "calibrate the Coolant Refill system periodically for accurate concentration",\n    "verify proper voltage supply to water and concentrate solenoids",\n    "check coolant level sensor functionality regularly",\n    "use appropriate nozzle size (1/2 inch) for thick coolant concentrates"\n  ]\n}\n```',
 '\n\n```json\n{\n  "part_name": "Drive Belt",\n  "solutions": [\n    "Review the machine application and tooling",\n    "Adjust the belt tension to Haas specifications",\n    "Follow the correct belt handling procedures",\n    "Remove debris or foreign objects in the belt path",\n    "Inspect or replace the motor standoffs/isolators",\n    "Inspect or replace damaged pulley",\n    "Replace worn belt",\n    "Check for coolant or oil leaks in the system",\n    "Ensure belt path is clear from rubbing on hoses/sheet metal",\n    "Verify pulley tooth profile integrity",\n    "Prevent coolant contamination on mill spindle belts",\n    "Check gearbox for oil leaks affecting belts"\n  ]\n}\n```',
 '\n\n```json\n{\n  "part_name": "Electrical Safety Door Interlocks",\n  "solutions": [\n    "Replace the switch head (P/N 93-2309) if damaged or worn",\n    "Check the switch and key alignment",\n    "Measure the voltage at the I/O PCB to ensure power supply",\n    "Inspect door rollers and tracks for contamination or loose components",\n    "Align interlock components if necessary",\n    "Test the interlock function by running the spindle above 1000 RPM with doors closed",\n    "Verify voltage presence at specified connectors on the control PCB (e.g., P29/P30 for CHC or P40/P41 for NGC)"\n  ]\n}\n```',
 '\n\n```json\n{\n  "part_name": "Foot Pedal",\n  "solutions": [\n    "Check and clean under the foot pedal to remove metal chips or debris ensuring full travel",\n    "Inspect cables for visible damage and verify proper connections",\n    "Check pedal spring for damage or loss of tension and replace if necessary",\n    "Ensure continuity across the foot pedal switch and replace if faulty",\n    "Adjust the metal flag position to properly actuate the switch when the pedal is pressed"\n  ]\n}\n```',
 '\n\n```json\n{\n  "part_name": "Haas Oil Skimmer",\n  "solutions": [\n    "Replace scraper rings and skimmer belt periodically based on their condition",\n    "Empty the oil container when full",\n    "Replace coolant with clean coolant periodically based on its condition",\n    "Use an electrical timer to automatically start and stop the Oil Skimmer",\n    "Ensure both coolant chambers are filled up to the drain level"\n  ]\n}\n```',
 '\n\n```json\n{\n  "part_name": "Haas Oil Skimmer",\n  "solutions": [\n    "perform regular maintenance on the Haas Oil Skimmer",\n    "follow installation instructions for proper setup (refer to linked guide)",\n    "inspect and maintain components shown in the provided diagrams"\n  ]\n}\n```',
 '\n\n```json\n{\n  "part_name": "Haas Oil Skimmer",\n  "solutions": [\n    "Properly align and secure the motor drive shaft set screw",\n    "Clean the oil skimmer and coolant tank if oil is too viscous",\n    "Check and replace damaged O-rings",\n    "Clean and refill chambers with clean coolant if full of dirty oil",\n    "Inspect for leaks in the chamber",\n    "Ensure no obstructions on the oil skimmer and coolant tank edge",\n    "Ensure secure electrical connections and reset GFCI if tripped"\n  ]\n}\n```',
 '\n\n```json\n{\n  "part_name": "High Pressure Flood Coolant (HPFC)",\n  "solutions": [\n    "Ensure all coolant nozzle valves are open to reduce pump noise",\n    "Check and refill coolant levels if low",\n    "Align the pump properly by adjusting standoffs if misaligned",\n    "Replace the filter cover when the O-ring is pushed out",\n    "Reinstall and secure the pressure relief set screw with threadlocker",\n    "Verify PVC plumbing integrity and reassemble if detached",\n    "Upgrade outdated HPFC pumps with current production models",\n    "Check power phasing to ensure pump motor runs in the correct direction",\n    "Confirm jumper placement and 12V input on motor drive PCB",\n    "Replace oversized hose clamps with appropriate size",\n    "Retrofit kinked pick-up hoses with spring-reinforced versions"\n  ]\n}\n```',
 '\n\n```json\n{\n  "part_name": "Haas Robot Package (HRP)",\n  "solutions": [\n    "Inspect the grippers fingers for wear every 6 months or when setting up a new job",\n    "Inspect the gripper airlines and fittings for wear or damage every 6 months",\n    "Inspect the air regulator and airline for wear or damage every 6 months",\n    "Replace the axis grease/oil every 3-4 years depending on HRP model",\n    "Regularly replace controller battery every 4 years",\n    "Check robot batteries every 7 months when stored/powered down",\n    "Replace robot batteries annually in active applications"\n  ]\n}\n```',
 '\n\n```json\n{\n  "part_name": "HRP (Haas Robot Package)",\n  "solutions": [\n    "Release the E-Stop and press RESET to clear the alarm. Then press the E-Stop and press F1 to connect the robot",\n    "Reduce part weight. See layout drawings for the payload specifications for each robot size",\n    "Update robot software again before using the robot",\n    "Power cycle the Robot Control and press RESET on the machine",\n    "Verify all robot estops are released and check estop wiring integrity",\n    "Increase Modbus TCP Timeout & Disable DHCP for connection issues",\n    "Connect & Calibrate Haas Robot if arm moved during power off",\n    "Check RJ45 to USB adapter functionality and replace if defective",\n    "Redo Master/Quick Master procedure if robot joints are misaligned",\n    "Re-upload configuration files from HBC to apply safety parameters",\n    "Reinitialize robot and make an image backup",\n    "Verify JP1 jumper installation on SIO PCB",\n    "Add machine dwell to Post Run sequence for job scheduling recovery",\n    "Install auto window install kit for M180/M181 command functionality",\n    "Update MAC Address in system via Haas Service",\n    "Correct TB1-B/TB3-B connector placement and wiring",\n    "Add more points to robot motion file for smoother motion",\n    "Install K9/K10 relays on I/O PCB",\n    "Follow DCS Cartesian Position Check Zone procedure",\n    "Replace robot arm batteries and perform Quick Mastering",\n    "Re-Teach program points to stay within axis travel limits",\n    "Install ferrite filters on communication cables",\n    "Set Fanuc Controller mode switch to Auto mode",\n    "Check/Replace fuse on Safe I/O board",\n    "Lower feed rate and verify DCS zone configuration",\n    "Clear chain errors and verify safety signal wiring"\n  ]\n}\n```',
 '\n\n```json\n{\n  "part_name": "Hydraulic Power Unit",\n  "solutions": [\n    "Check the coolant collector for blockage",\n    "Ensure fittings are tightened and hoses are replaced if damaged",\n    "Replace missing or damaged O-rings/plugs on manifold assembly",\n    "Check/tighten pickup tube to prevent air leaks",\n    "Re-configure return and pick-up pipes to reduce air bubbles",\n    "Maintain correct oil level in the HPU",\n    "Clean or replace clogged pressure filter and intake screen",\n    "Verify cooling fans are operational",\n    "Enable Setting 216 for hydraulic system shutoff during idle",\n    "Check electrical phasing to ensure pump motor runs correctly",\n    "Inspect and replace bent/damaged pressure adjustment valves",\n    "Troubleshoot solenoid voltage and clean valves if necessary",\n    "Clear blockages in coolant return lines to prevent contamination",\n    "Check for oil leaks at intake pipes and apply thread sealant",\n    "Replace damaged pressure gauges and secure snubber screws",\n    "Reduce clamp force, RPM, or duty cycle to minimize air entrapment",\n    "Ensure heat exchanger is clean and functional"\n  ]\n}\n```',
 '\n\n```json\n{\n  "part_name": "Hydraulic Tailstock",\n  "solutions": [\n    "Use M21 or the foot pedal to maintain pressure on the part",\n    "Use Spindle Speed Variation (SSV) to control part chatter",\n    "Align the tailstock",\n    "Set pressure correctly for part material, diameter, and length",\n    "Inspect the encoder string for damage or contamination",\n    "Check the operation of the hydraulic power unit (HPU) and solenoids",\n    "Adjust hydraulic pressure if set too low",\n    "Inspect linear guides and way covers for chip buildup or obstructions",\n    "Set tailstock hold point according to the specified settings",\n    "Clean and align the encoder comb strip",\n    "Verify spindle speed variation parameters are properly configured",\n    "Ensure way covers move smoothly without binding"\n  ]\n}\n```',
 '\n\n```json\n{\n  "part_name": "Lathe HPU Clear Work holding",\n  "solutions": [\n    "Check if the oil tank is full using dipstick, sight glass, or clear container when HPU is off",\n    "Ensure the hydraulic union drain hose slopes down entirely to the tank",\n    "Verify that the gauge returns to zero after the machine has been on and turned off",\n    "Clean solenoid valves per Haas HPU troubleshooting guide",\n    "Check all electrical connections to solenoids, HPU, fans, and sensors are secure",\n    "Inspect the pump intake screen for clogs",\n    "Confirm hydraulic pressure readings match the control gauge page",\n    "Check for bubbles or coolant contamination in the oil",\n    "Verify HPU cooling fans are operational (if applicable)",\n    "Ensure the hydraulic pressure does not fluctuate excessively"\n  ]\n}\n```',
 '\n\n```json\n{\n  "part_name": "I/O PCB",\n  "solutions": [\n    "Check the axis brake cable and voltage output",\n    "Swap the tool changer relays on the I/O PCB",\n    "Verify power supply voltages to the I/O PCB",\n    "Inspect circuit breakers and fuses on the Power Distribution PCB",\n    "Ensure all connections and cables are secure and undamaged",\n    "Check for burnt components or traces on the I/O PCB",\n    "Test the 5 VDC and 12 VDC outputs from the Low Voltage Power Supply",\n    "Confirm proper 3-phase 120 VAC and 240 VAC supplies",\n    "Inspect the GFCI outlet for tripping",\n    "Verify functionality of coolant and TSC circuit breakers",\n    "Check conveyor circuit breaker status",\n    "Measure axis brake voltage between 18-30 VDC"\n  ]\n}\n```',
 '\n\n```json\n{\n  "part_name": "I/O PCB",\n  "solutions": [\n    "Troubleshoot the I/O PCB Low Volt Power Supply (LVPS)",\n    "Update the I/O configuration using a USB device with the correct configuration files",\n    "Verify CAN node I/O configuration settings",\n    "Check all 120V outputs for possible shorts to earth ground",\n    "Inspect wiring, pins, and connectors for circuit integrity",\n    "Update I/O PCB Main and Tool Changer firmware to the latest version",\n    "Verify proper termination of CAN communication cables",\n    "Check RJ-45 cable connections between Maincon PCB and I/O PCB",\n    "Inspect I/O PCB for damaged components or solder issues",\n    "Verify 120V/240V power supply inputs to the I/O PCB",\n    "Check for ground faults in programmable coolant circuits",\n    "Inspect tool changer motor outputs for short circuits",\n    "Verify proper operation of TSC cooling fan",\n    "Check hydraulic union safety device connections at P12",\n    "Test low voltage circuit components (+24V, +15V, +12V)",\n    "Inspect PCB for missing/broken components or solder bridges",\n    "Verify proper door interlock connections and functionality",\n    "Check spindle load circuit components for faults",\n    "Inspect estop circuit for momentary disconnects",\n    "Verify correct operation of coolant pump and chip conveyor systems"\n  ]\n}\n```',
 '\n\n```json\n{\n  "part_name": "Chuck",\n  "solutions": [\n    "Grease the chuck jaws",\n    "Perform chuck multi-point inspection",\n    "Clean the chuck"\n  ]\n}\n```\n\n```json\n{\n  "part_name": "Barfeeders",\n  "solutions": [\n    "Grease the bar feed push rod and bushing",\n    "Grease the ballscrew, V-roller tracks, and rotation",\n    "Check belt tension",\n    "Check push rod alignment"\n  ]\n}\n```',
 '\n\n```json\n{\n  "part_name": "Lathe Parts Catcher",\n  "solutions": [\n    "Ensure proper lubrication and remove chip buildup",\n    "Check and replace faulty rotary damper",\n    "Ensure proper air supply connections and solenoid functionality",\n    "Replace worn rotary damper with updated part (P/N 59-2164)"\n  ]\n}\n```',
 '\n\n```json\n{\n  "part_name": "Standard Coolant System",\n  "solutions": [\n    "Clean the filter screen as required",\n    "Inspect the coolant level weekly",\n    "Inspect the coolant concentration and fill out the Mixture - Maintenance Log sheet weekly",\n    "Completely clean the coolant tank and replace the coolant every six months",\n    "Verify coolant refill is operating correctly every six months",\n    "Inspect turret coolant lines for chips monthly"\n  ]\n}\n```',
 '\n\n```json\n{\n  "part_name": "Live Tooling",\n  "solutions": [\n    "Inspect the servo motor for contamination or damage",\n    "Check the drive belt for contamination, damage, and correct tension",\n    "Align the live tooling bearing cap and adjust alignment if necessary",\n    "Examine and replace the live tooling bearing if faulty",\n    "Inspect and replace the drive castle spring if broken",\n    "Ensure the drive castle is properly seated and retaining screw is tightened",\n    "Check and refill oil level in the live tooling (gear drive only)",\n    "Inspect live tooling gears for damage (gear drive only)"\n  ]\n}\n```',
 '\n\n```json\n{\n  "part_name": "Mechanical Bijur Lubrication Pump",\n  "solutions": [\n    "Ensure the oil level is adequate",\n    "Check and replace the pressure switch if faulty",\n    "Verify electrical connections and voltage supply to the pump",\n    "Clean or replace the clogged oil filter",\n    "Inspect and repair leaking fittings in the system",\n    "Clear blockages in oil lines or metering units",\n    "Test the system for leaks and ensure pressure integrity",\n    "Check the worm screw operation in the oil tank",\n    "Remove sludge or debris from the oil reservoir"\n  ]\n}\n```',
 '\n\n```json\n{\n  "part_name": "Mist Condenser",\n  "solutions": [\n    "ensure proper installation of gaskets and vibration isolators",\n    "verify correct motor phasing to maintain airflow direction",\n    "clean and reinstall clogged mesh filters",\n    "check and secure all electrical connections and wiring",\n    "route hoses with minimal bends to maintain efficiency",\n    "inspect rubber bushings for damage or improper installation",\n    "confirm jumper installation on TMD card (P3 pins 1-2)",\n    "test mist condenser fan operation via MDI program (M158/M159)"\n  ]\n}\n```',
 '\n\n```json\n{\n  "part_name": "Proximity Sensor",\n  "solutions": [\n    "Re-route cables away from high power sources and apply ferrite bead",\n    "Clean and reseat connectors, address contamination",\n    "Clean metal particles from the sensor face",\n    "Ensure the gap between sensor face and trip flag does not exceed 0.126 inches",\n    "Troubleshoot cables or I/O PCB for faults",\n    "Check and secure proximity sensor connector connections",\n    "Inspect cables for damage or open connections",\n    "Test voltage at the sensor and check diagnostic bit status",\n    "Separate sensor cables from high-power sources",\n    "Check axis grid offset parameter settings"\n  ]\n}\n```',

In [30]:
def convert_json_to_dict(content):
    if "```json" in content:
        data = content.split("```json")[1].split("```")[0]
        return eval(data)
    elif "```" in content:
        data = content.split("```")[1]
        return eval(data)
    else:
        return eval(content)
    
df['part_name'].apply(lambda x:convert_json_to_dict(x))
df['solutions'].apply(lambda x:convert_json_to_dict(x))

SyntaxError: invalid syntax (<string>, line 1)

In [28]:
df['part_name'] = [convert_json_to_dict(i)['part_name'] for i in result]
df['solutions'] = [convert_json_to_dict(i)['solutions'] for i in result]

SyntaxError: invalid syntax (<string>, line 1)

In [29]:
for i,j in enumerate(result):
    print(i)
    convert_json_to_dict(i)['part_name']

NameError: name 'result' is not defined

In [46]:
df['part_name'] = [eval(i.split("```json")[1].split("```")[0])['part_name'] for i in result]
df['solutions'] = [eval(i.split("```json")[1].split("```")[0])['solutions'] for i in result]

In [47]:
df['part_name'].value_counts()

part_name
Turret Indexer Assembly                   3
Haas Oil Skimmer                          3
Chip Conveyor                             2
I/O PCB                                   2
Lathe Spindle                             1
Mist Condenser                            1
Proximity Sensor                          1
PSUP PCB                                  1
Servo Amplifier                           1
Sigma 5 Axis Servo Motor and Cables       1
Solenoid                                  1
Spindle Minimum Lubrication System        1
Live Tooling                              1
Spindle Non-Contact Encoder (NCE)         1
Coolant Pump Impeller                     1
Through-Tool Air Blast (TAB)              1
TSC Pump                                  1
Vector Drive                              1
VMC Side Mount Tool Changer Double Arm    1
Mechanical Bijur Lubrication Pump         1
Lathe Parts Catcher                       1
Standard Coolant System                   1
BMT65/75 Turret Live Tool Drive           1
Chuck                                     1
Lathe HPU Clear Work holding              1
Hydraulic Tailstock                       1
Hydraulic Power Unit                      1
HRP (Haas Robot Package)                  1
Haas Robot Package (HRP)                  1
High Pressure Flood Coolant (HPFC)        1
Foot Pedal                                1
Electrical Safety Door Interlocks         1
Drive Belt                                1
Coolant Refill                            1
Coolant Refill System                     1
Chip Auger                                1
Way Cover                                 1
Name: count, dtype: int64

In [48]:
df

,file_name,title,content,part_name,solutions
0,BMT65_75 - Turret Indexer Assembly - Troublesh...,BMT65_75 - Turret Indexer Assembly - Troublesh...,## BMT65/75 - Turret Indexer Assembly - Troubl...,Turret Indexer Assembly,"[Check the incoming air supply, Check the volt..."
1,BMT65_75 Turret - Live Tool Drive - Alignment.txt,BMT65_75 Turret - Live Tool Drive - Alignment,## BMT65/75 Turret - Live Tool Drive - Alignme...,BMT65/75 Turret Live Tool Drive,[Check the alignment of the live tool drive in...
2,Chip Auger - Haas Service Manual.txt,Chip Auger - Haas Service Manual,### 6 - Chip Auger\n\n\n###### https://www.haa...,Chip Auger,[Inspect the auger motor start capacitor for d...
3,Chip Conveyor - Lathe - Haas Service Manual.txt,Chip Conveyor - Lathe - Haas Service Manual,### 9 - Chip Conveyor - Lathe\n\n\n###### http...,Chip Conveyor,[Check for a short circuit in the motor or the...
4,Chip Conveyor - UMC - Haas Service Manual.txt,Chip Conveyor - UMC - Haas Service Manual,### 8 - Chip Conveyor - UMC\n\n\n###### https:...,Chip Conveyor,[ensure the conveyor drive cable is routed pro...
5,Coolant Refill - Calibration.txt,Coolant Refill - Calibration,## Coolant Refill - Calibration\n\n\nhttps://w...,Coolant Refill System,[Adjust the Concentrate Adjustment value based...
6,Coolant Refill - Haas Service Manual.txt,Coolant Refill - Haas Service Manual,### 10 - Coolant Refill\n\n\n###### https://ww...,Coolant Refill,[make sure the coolant tank float operates cor...
7,Drive Belt - Troubleshooting Guide.txt,Drive Belt - Troubleshooting Guide,## Drive Belt - Troubleshooting Guide\n\n\nhtt...,Drive Belt,"[Review the machine application and tooling, A..."
8,Electrical Safety Door Interlocks - Troublesho...,Electrical Safety Door Interlocks - Troublesho...,## Electrical Safety Door Interlocks - Trouble...,Electrical Safety Door Interlocks,[Replace the switch head (P/N 93-2309) if dama...
9,Foot Pedal - Troubleshooting Guide - NGC.txt,Foot Pedal - Troubleshooting Guide - NGC,## Foot Pedal - Troubleshooting Guide - NGC\n\...,Foot Pedal,[Check and clean under the foot pedal to remov...
10,Haas Oil Skimmer - Installation - AD0480.txt,Haas Oil Skimmer - Installation - AD0480,## Haas Oil Skimmer - Installation - AD0480\n\...,Haas Oil Skimmer,[Replace scraper rings and skimmer belt period...
11,Haas Oil Skimmer - Maintenence - AD0481.txt,Haas Oil Skimmer - Maintenence - AD0481,## Haas Oil Skimmer - Maintenence - AD0481\n\n...,Haas Oil Skimmer,[perform regular maintenance on the Haas Oil S...
12,Haas Oil Skimmer Troubleshooting Guide.txt,Haas Oil Skimmer Troubleshooting Guide,## Haas Oil Skimmer Troubleshooting Guide\n\n\...,Haas Oil Skimmer,[Properly align and secure the motor drive sha...
13,High Pressure Flood Coolant - Haas Service Man...,High Pressure Flood Coolant - Haas Service Manual,### 11 - High Pressure Flood Coolant\n\n\n####...,High Pressure Flood Coolant (HPFC),[Ensure all coolant nozzle valves are open to ...
14,HRP - Maintenance - Haas Service Manual.txt,HRP - Maintenance - Haas Service Manual,### 12 - HRP - Maintenance\n\n\n###### https:/...,Haas Robot Package (HRP),[Inspect the grippers fingers for wear every 6...
15,HRP - Troubleshooting - Haas Service Manual.txt,HRP - Troubleshooting - Haas Service Manual,### 13 - HRP - Troubleshooting\n\n\n###### htt...,HRP (Haas Robot Package),[Release the E-Stop and press RESET to clear t...
16,Hydraulic Power Unit - Troubleshooting Guide.txt,Hydraulic Power Unit - Troubleshooting Guide,## Hydraulic Power Unit - Troubleshooting Guid...,Hydraulic Power Unit,"[Check the coolant collector for blockage, Ens..."
17,Hydraulic Tailstock - Troubleshooting Guide.txt,Hydraulic Tailstock - Troubleshooting Guide,## Hydraulic Tailstock - Troubleshooting Guide...,Hydraulic Tailstock,[Use M21 or the foot pedal to maintain pressur...
18,ID0014_Rev_A.txt,ID0014_Rev_A,# HPU Inspection Report\n\nLathe HPU Clear Wor...,Lathe HPU Clear Work holding,"[Check if the oil tank is full using dipstick,..."
19,I_O PCB - Troubleshooting Guide - CHC.txt,I_O PCB - Troubleshooting Guide - CHC,## I/O PCB - Troubleshooting Guide - CHC\n\n\n...,I/O PCB,[Check the axis brake cable and voltage output...
20,I_O PCB - Troubleshooting Guide - NGC.txt,I_O PCB - Troubleshooting Guide - NGC,## I/O PCB - Troubleshooting Guide - NGC\n\n\n...,I/O PCB,[Troubleshoot the I/O PCB Low Volt Power Suppl...
21,Lathe - Maintenance - Haas Service Manual.txt,Lathe - Maintenance - Haas Service Manual,### 20 - Lathe - Maintenance\n\n\n##### https:...,Chuck,"[Grease the chuck jaws, Perform chuck multi-po..."
22,Lathe - Parts Catcher - Haas Service Manual.txt,Lathe - Parts Catcher - Haas Service Manual,### 12 - Lathe - Parts Catcher\n\n\n###### htt...,Lathe Parts Catcher,[Ensure proper lubrication and remove chip bui...
23,Lathe Maintenance Schedule.txt,Lathe Maintenance Schedule,## Lathe Maintenance Schedule\n\n\nhttps://www...,Standard Coolant System,"[Clean the filter screen as required, Inspect ..."
24,Live Tooling - Troubleshooting Guide.txt,Live Tooling - Troubleshooting Guide,## Live Tooling - Troubleshooting Guide\n\n\nh...,Live Tooling,[Inspect the servo motor for contamination or ...
25,Mechanical Bijur Lubrication Pump - Troublesho...,Mechanical Bijur Lubrication Pump - Troublesho...,## Mechanical Bijur Lubrication Pump - Trouble...,Mechanical Bijur Lubrication Pump,"[Ensure the oil level is adequate, Check and r..."
26,Mist Condenser - Haas Service Manual.txt,Mist Condenser - Haas Service Manual,### 15 - Mist Condenser\n\n\n###### https://ww...,Mist Condenser,[ensure proper installation of gaskets and vib...
27,Proximity Sensor - Troubleshooting Guide.txt,Proximity Sensor - Troubleshooting Guide,## Proximity Sensor - Troubleshooting Guide\n\...,Proximity Sensor,[Re-route cables away from high power sources ...
28,PSUP PCB - Troubleshooting Guide - NGC.txt,PSUP PCB - Troubleshooting Guide - NGC,## PSUP PCB - Troubleshooting Guide - NGC\n\n\...,PSUP PCB,[ensure the circuit breakers are properly seat...
29,Servo Amplifier - Troubleshooting Guide - CHC.txt,Servo Amplifier - Troubleshooting Guide - CHC,## Servo Amplifier - Troubleshooting Guide - C...,Servo Amplifier,"[Check cables for contamination or damage, Per..."
30,Sigma 5 - Axis Servo Motor and Cables - Troubl...,Sigma 5 - Axis Servo Motor and Cables - Troubl...,## Sigma 5 - Axis Servo Motor and Cables - Tro...,Sigma 5 Axis Servo Motor and Cables,[Inspect cables and connectors for damage or i...
31,Solenoid - Troubleshooting Guide.txt,Solenoid - Troubleshooting Guide,## Solenoid - Troubleshooting Guide\n\n\nhttps...,Solenoid,[Ensure correct air pressure and flow to the s...
32,Spindle - Lathe - Troubleshooting Guide.txt,Spindle - Lathe - Troubleshooting Guide,## Spindle - Lathe - Troubleshooting Guide\n\n...,Lathe Spindle,[verify spindle drivetrain component alignment...
33,Spindle Minimum Lubrication System - Troublesh...,Spindle Minimum Lubrication System - Troublesh...,## Spindle Minimum Lubrication System - Troubl...,Spindle Minimum Lubrication System,"[Make sure the reservoir has enough oil, Inspe..."
34,Spindle Non-Contact Encoder (NCE) - Troublesho...,Spindle Non-Contact Encoder (NCE) - Troublesho...,## Spindle Non-Contact Encoder (NCE) - Trouble...,Spindle Non-Contact Encoder (NCE),[Ensure the Wye-Delta contactors are operating...
35,Standard Flood Coolant - Haas Service Manual.txt,Standard Flood Coolant - Haas Service Manual,### 3 - Standard Flood Coolant\n\n\n###### htt...,Coolant Pump Impeller,[Inspect the impeller for damage or debris and...
36,Through-Tool Air Blast - Haas Service Manual.txt,Through-Tool Air Blast - Haas Service Manual,### 13 - Through-Tool Air Blast\n\n\n###### ht...,Through-Tool Air Blast (TAB),[Ensure the TAB system operates correctly by v...
37,TSC-300_1K - Troubleshooting Guide - NGC.txt,TSC-300_1K - Troubleshooting Guide - NGC,## TSC-300/1K - Troubleshooting Guide - NGC\n\...,TSC Pump,[check the circuit breakers and fuses on the p...
38,Turret Indexer Assembly - SL-10_30 ST-10_15 - ...,Turret Indexer Assembly - SL-10_30 ST-10_15 - ...,## Turret Indexer Assembly - SL-10/30 ST-10/15...,Turret Indexer Assembly,"[Check the incoming air supply, Check the volt..."
39,Turret Indexer Assembly - ST-20_55 series - Tr...,Turret Indexer Assembly - ST-20_55 series - Tr...,## Turret Indexer Assembly - ST-20/55 series -...,Turret Indexer Assembly,[Check the incoming air supply for correct pre...
40,Vector Drive - Troubleshooting Guide - NGC.txt,Vector Drive - Troubleshooting Guide - NGC,## Vector Drive - Troubleshooting Guide - NGC\...,Vector Drive,[Inspect the Vector Drive and Wye-Delta contac...
41,VMC Side Mount Tool Changer - Double Arm - Rep...,VMC Side Mount Tool Changer - Double Arm - Rep...,## VMC Side Mount Tool Changer - Double Arm - ...,VMC Side Mount Tool Changer Double Arm,[ensure no tool is present in the spindle and ...
42,Way Cover - Troubleshooting Guide.txt,Way Cover - Troubleshooting Guide,## Way Cover - Troubleshooting Guide\n\n\nhttp...,Way Cover,"[Replace damaged wipers, Ensure correct coolan..."

In [6]:
## gpt_version

# df.loc[df['part_name'] == "Haas Robot Package (HRP)","part_name"] = "Haas Robot Package"
# part_category_mapping = {
#     # 主轴与传动系统（Spindle & Drive）
#     "Drive Belt": "Spindle & Drive",
#     "Lathe Spindle": "Spindle & Drive",
#     "Sigma 5 - Axis Servo Motor and Cables": "Spindle & Drive",
#     "Servo Amplifier": "Spindle & Drive",
#     "Vector Drive": "Spindle & Drive",
#     "Spindle Non-Contact Encoder (NCE)": "Spindle & Drive",
#     "BMT65/75 Turret - Live Tool Drive": "Spindle & Drive",  # 合并到 Spindle & Drive
#     "VMC Side Mount Tool Changer - Double Arm": "Spindle & Drive",  # 合并到 Spindle & Drive
# 
#     # 冷却与润滑系统（Coolant & Lubrication）
#     "Coolant Refill": "Coolant & Lubrication",
#     "High Pressure Flood Coolant": "Coolant & Lubrication",
#     "Standard Flood Coolant": "Coolant & Lubrication",
#     "Mist Condenser": "Coolant & Lubrication",
#     "Spindle Minimum Lubrication System": "Coolant & Lubrication",
#     "Mechanical Bijur Lubrication Pump": "Coolant & Lubrication",
#     "Haas Oil Skimmer": "Coolant & Lubrication",
#     "Through-Tool Air Blast (TAB)": "Coolant & Lubrication",
#     "TSC-300/1K": "Coolant & Lubrication",
# 
#     # 电气与控制系统（Electrical & Control）
#     "PSUP PCB": "Electrical & Control",
#     "I/O PCB": "Electrical & Control",
#     "Electrical Safety Door Interlocks": "Electrical & Control",
#     "Proximity Sensor": "Electrical & Control",
#     "Solenoid": "Electrical & Control",
# 
#     # 液压与气动系统（Hydraulic & Pneumatic）
#     "Hydraulic Power Unit": "Hydraulic & Pneumatic",
#     "Lathe HPU": "Hydraulic & Pneumatic",
#     "Hydraulic Tailstock": "Hydraulic & Pneumatic",
# 
#     # 机械组件（Mechanical Components）
#     "Chip Auger": "Mechanical Components",
#     "Chip Conveyor": "Mechanical Components",
#     "Way Cover": "Mechanical Components",
#     "Foot Pedal": "Mechanical Components",
#     "Lathe": "Mechanical Components",  # 合并 Lathe 到此类
# 
#     # 自动化与机器人系统（Automation & Robotics）
#     "Haas Robot Package": "Automation & Robotics",
#     "Parts Catcher": "Automation & Robotics",
#     "Turret Indexer Assembly": "Spindle & Drive",
#     "Live Tooling": "Spindle & Drive",
# }

In [22]:
response = client.chat.completions.create(
    model="deepseek-reasoner",
    messages=[{"role":"system","content":"""我将会给你一批零件的名称，你需要把以下零件归类到以下6个大类中：
    Spindle & Drive\Mechanical Components\Automation & Robotics\Coolant & Lubrication\Electrical & Control\Hydraulic & Pneumatic
    然后返回一个对应的码表,不需要有其他的解释
         #Output Format:
         {
         "零件的名称":"归类的大类名称",
         "零件的名称":"归类的大类名称",
         ...
         }"""
               },
              {"role":"user","content":f"这是零件名称：{list(set(df['part_name']))}"}],
    temperature=0.01
)

In [24]:
df['category'] = df['part_name'].map(eval(response.choices[0].message.content.strip()
                                          .split("```json")[1].split("```")[0]))

In [25]:
df['category'].value_counts()

category
Coolant & Lubrication    15
Electrical & Control      9
Mechanical Components     6
Automation & Robotics     5
Hydraulic & Pneumatic     5
Spindle & Drive           3
Name: count, dtype: int64

In [78]:
df[['part_name','category']]

                                   part_name               category
0                    Turret Indexer Assembly       Tooling & Turret
1          BMT65/75 Turret - Live Tool Drive        Spindle & Drive
2                                 Chip Auger  Mechanical Components
3                              Chip Conveyor  Mechanical Components
4                              Chip Conveyor  Mechanical Components
5                             Coolant Refill  Coolant & Lubrication
6                             Coolant Refill  Coolant & Lubrication
7                                 Drive Belt        Spindle & Drive
8          Electrical Safety Door Interlocks   Electrical & Control
9                                 Foot Pedal  Mechanical Components
10                          Haas Oil Skimmer  Coolant & Lubrication
11                          Haas Oil Skimmer  Coolant & Lubrication
12                          Haas Oil Skimmer  Coolant & Lubrication
13               High Pressure Flood Coolant  Coolant & Lubrication
14                        Haas Robot Package  Automation & Robotics
15                        Haas Robot Package  Automation & Robotics
16                      Hydraulic Power Unit  Hydraulic & Pneumatic
17                       Hydraulic Tailstock  Hydraulic & Pneumatic
18                                 Lathe HPU  Hydraulic & Pneumatic
19                                   I/O PCB   Electrical & Control
20                                   I/O PCB   Electrical & Control
21                                     Lathe  Mechanical Components
22                             Parts Catcher  Automation & Robotics
23                                     Lathe  Mechanical Components
24                              Live Tooling       Tooling & Turret
25         Mechanical Bijur Lubrication Pump  Coolant & Lubrication
26                            Mist Condenser  Coolant & Lubrication
27                          Proximity Sensor   Electrical & Control
28                                  PSUP PCB   Electrical & Control
29                           Servo Amplifier        Spindle & Drive
30     Sigma 5 - Axis Servo Motor and Cables        Spindle & Drive
31                                  Solenoid   Electrical & Control
32                             Lathe Spindle        Spindle & Drive
33        Spindle Minimum Lubrication System  Coolant & Lubrication
34         Spindle Non-Contact Encoder (NCE)        Spindle & Drive
35                    Standard Flood Coolant  Coolant & Lubrication
36              Through-Tool Air Blast (TAB)  Coolant & Lubrication
37                                TSC-300/1K  Coolant & Lubrication
38                   Turret Indexer Assembly       Tooling & Turret
39                   Turret Indexer Assembly       Tooling & Turret
40                              Vector Drive        Spindle & Drive
41  VMC Side Mount Tool Changer - Double Arm        Spindle & Drive
42                                 Way Cover  Mechanical Components

In [26]:
df.to_excel("../builder/classified_ds.xlsx",index=False)